/* app-lang.js — VaultNest · translations (he/en), T(), passphrase word lists
   Loaded by app-boot.js in a fixed order with ?v=<version>. Last line registers the module. */
'use strict';
/* ================= i18n ================= */
const LANGS=[{c:'he',n:'עברית'},{c:'en',n:'English'}]; // ru/es/ar: next round (keys fall back to English)
const RTL=['he','ar'];
const LANG={
he:{
app_sub:'הכספת שלי',skip_link:'דלג לתוכן',
lock_title:'הכספת נעולה',master_pw:'סיסמה ראשית',unlock:'פתח',unlocking:'פותח…',wrong_pw:'סיסמה שגויה',
wait_s:'יותר מדי ניסיונות. נסה שוב בעוד {s} שניות',use_bio:'טביעת אצבע',use_pin:'קוד',use_pattern:'סימון',
forgot:'שכחתי את הסיסמה',rec_enter:'הזן את קוד השחזור',rec_wrong:'קוד השחזור שגוי',rec_ok_set_new:'הקוד נכון. בחר סיסמה ראשית חדשה',
back:'חזרה',cancel:'ביטול',save:'שמור',delete:'מחק',edit:'ערוך',close:'סגור',copy:'העתק',copied:'הועתק',show:'הצג',hide:'הסתר',
open:'פתח',done:'סיום',next:'הבא',skip:'דלג',confirm:'אישור',later:'אחר כך',continue:'המשך',
ob1_t:'ברוך הבא לכספת',ob1_d:'מקום אחד לסיסמאות, כרטיסי אשראי, קודים, מסמכים ותמונות חשובות.',
ob2_t:'הכול מוצפן, הכול אצלך',ob2_d:'המידע מוצפן ב-AES-256 לפני שהוא נשמר, ונשאר רק במכשיר הזה. שום דבר לא נשלח לשרת.',
ob3_t:'סיסמה ראשית אחת',ob3_d:'היא המפתח לכל השאר, ואין לנו דרך לשחזר אותה. לכן תקבל גם קוד שחזור — כדאי לרשום אותו על נייר.',
ob4_t:'פתיחה מהירה',ob4_d:'אחרי ההגדרה אפשר לפתוח עם טביעת אצבע, קוד או סימון על המסך.',
ob5_t:'גיבוי הוא הביטוח שלך',ob5_d:'אם המכשיר אבד או שנתוני הדפדפן נמחקו, רק קובץ גיבוי יחזיר את המידע. תוכן הגיבוי מוצפן.',
ob_start:'בוא נתחיל',
create_t:'יצירת סיסמה ראשית',create_d:'לפחות 10 תווים. משפט קצר שקל לך לזכור עדיף על מילה מסובכת.',
new_pw:'סיסמה ראשית חדשה',pw_confirm:'הקלד שוב',pw_mismatch:'הסיסמאות לא תואמות',pw_short:'צריך לפחות 10 תווים',
pw_weak_warn:'הסיסמה הזו חלשה, וכל האבטחה של הכספת נשענת עליה. להמשיך בכל זאת?',create_btn:'צור את הכספת',creating:'יוצר ומצפין…',
restore_existing:'יש לי כבר גיבוי — שחזר ממנו',
str_0:'חלשה מאוד',str_1:'חלשה',str_2:'בינונית',str_3:'חזקה',str_4:'חזקה מאוד',
rec_t:'קוד השחזור שלך',rec_d:'זה הקוד היחיד שיפתח את הכספת אם תשכח את הסיסמה הראשית. רשום אותו על נייר ושמור במקום בטוח — לא בטלפון. הוא לא יוצג שוב.',
rec_check:'רשמתי את הקוד במקום בטוח',rec_copy:'העתק קוד',
quick_offer_t:'להוסיף פתיחה מהירה?',quick_offer_d:'כדי לא להקליד את הסיסמה הראשית בכל פעם. אפשר לשנות בכל רגע בהגדרות.',
search_ph:'חיפוש בכספת…',cat_all:'הכול',cat_fav:'מועדפים',files:'קבצים ותמונות',
t_login:'סיסמאות ואתרים',t_card:'כרטיסי אשראי',t_code:'קודים',t_wifi:'רשתות Wi-Fi',t_bank:'חשבונות בנק',t_identity:'מסמכים מזהים',t_note:'פתקים מאובטחים',
ts_login:'סיסמה לאתר או אפליקציה',ts_card:'כרטיס אשראי',ts_code:'קוד (אזעקה, דלת, כספת…)',ts_wifi:'רשת Wi-Fi',ts_bank:'חשבון בנק',ts_identity:'מסמך מזהה',ts_note:'פתק מאובטח',
add_item:'הוסף לכספת',add_what:'מה להוסיף?',add_files:'קבצים או תמונות',
gen_t:'מחולל סיסמאות',health_t:'בריאות הסיסמאות',settings:'הגדרות',about:'אודות',lock_now:'נעל עכשיו',
items_n:'{n} פריטים',
backup_nag:'עברו {d} ימים מהגיבוי האחרון.',backup_never:'עדיין לא יצרת גיבוי. בלי גיבוי, ניקוי נתוני הדפדפן ימחק את הכספת.',backup_now:'גבה עכשיו',
empty_list:'עדיין אין כאן כלום. לחץ על ״הוסף לכספת״ כדי להתחיל.',no_results:'לא נמצאו פריטים',
trash:'סל מחזור',trash_empty:'סל המחזור ריק',trash_note:'פריטים נמחקים מכאן לצמיתות אחרי 30 יום.',restore:'שחזר',delete_forever:'מחק לצמיתות',
moved_trash:'הועבר לסל המחזור',restored:'שוחזר',empty_trash:'רוקן את הסל',empty_trash_c:'למחוק לצמיתות את כל מה שבסל? אי אפשר לבטל.',
f_title:'שם',f_username:'שם משתמש / אימייל',f_password:'סיסמה',f_url:'כתובת אתר',f_notes:'הערות',f_cardholder:'שם בעל הכרטיס',
f_number:'מספר כרטיס',f_expiry:'תוקף',f_cvv:'CVV (3 ספרות בגב)',f_cardPin:'קוד סודי',f_issuer:'חברת אשראי / בנק',f_code:'קוד',
f_ssid:'שם הרשת',f_security:'סוג אבטחה',sec_none:'פתוחה (בלי סיסמה)',f_bankName:'בנק',f_branch:'סניף',f_account:'מספר חשבון',
f_docType:'סוג המסמך',f_fullName:'שם מלא',f_docNumber:'מספר מסמך',f_issued:'תאריך הנפקה',f_docExpiry:'תאריך תפוגה',f_fav:'סמן כמועדף',
title_ph_login:'למשל: Gmail, בנק הפועלים, נטפליקס',title_ph_card:'למשל: ויזה כאל',title_ph_code:'למשל: אזעקה בבית',title_ph_wifi:'למשל: הרשת בבית',
title_ph_bank:'למשל: חשבון עו״ש',title_ph_identity:'למשל: דרכון',title_ph_note:'למשל: קודי גיבוי של Google',
new_item:'פריט חדש',edit_item:'עריכה',need_title:'צריך לתת שם לפריט',saved:'נשמר',save_fail:'השמירה נכשלה: {e}',
del_confirm:'להעביר את ״{n}״ לסל המחזור?',del_forever_c:'למחוק לצמיתות? אי אפשר לבטל.',
open_site:'פתח אתר',created_at:'נוצר {d}',updated_at:'עודכן {d}',fav_on:'נוסף למועדפים',fav_off:'הוסר מהמועדפים',
reused_n:'משמשת ב-{n} פריטים',old_pw:'לא הוחלפה מעל שנה',
check_breach:'בדוק אם דלפה',breach_t:'בדיקת דליפות',
breach_consent:'הבדיקה שולחת לשירות Have I Been Pwned רק 5 תווים מתוך ״טביעה״ מוצפנת של הסיסמה — לא את הסיסמה עצמה ולא שום פרט אחר. להמשיך?',
breach_found:'הופיעה {n} פעמים בדליפות ידועות — מומלץ להחליף',breach_clean:'לא נמצאה בדליפות ידועות',breach_err:'הבדיקה נכשלה. יש חיבור לאינטרנט?',checking:'בודק…',
exp_soon:'פג תוקף בעוד {d} ימים',exp_past:'פג תוקף',
gen_length:'אורך: {n}',gen_lower:'אותיות קטנות (a-z)',gen_upper:'אותיות גדולות (A-Z)',gen_digits:'ספרות (0-9)',gen_symbols:'סימנים (!@#)',
gen_ambig:'בלי תווים דומים (O/0, l/1)',gen_new:'צור סיסמה',bits:'חוזק משוער: {b} ביט',
h_score:'ציון הכספת',h_weak:'סיסמאות חלשות',h_reused:'סיסמאות שחוזרות על עצמן',h_old:'לא הוחלפו מעל שנה',h_expiring:'כרטיסים ומסמכים שפג תוקפם או יפוג בקרוב',
h_breached:'סיסמאות שנמצאו בדליפות',h_all_good:'אין כאן בעיות',h_checkall:'בדוק את כל הסיסמאות בדליפות',h_checking:'בודק {i} מתוך {n}…',
h_none:'עדיין אין סיסמאות לבדוק.',h_note:'החוזק הוא הערכה לפי אורך וגיוון התווים — לא הבטחה.',
files_add:'הוסף קבצים',files_camera:'צלם',file_cat:'קטגוריה',file_name:'שם הקובץ',
fc_all:'הכול',fc_id:'תעודות',fc_money:'כספים',fc_home:'בית',fc_car:'רכב',fc_health:'בריאות',fc_other:'אחר',
files_empty:'אין עדיין קבצים. אפשר להוסיף תמונות, PDF וכל קובץ אחר — הם מוצפנים לפני השמירה.',
encrypting:'מצפין {i} מתוך {n}…',file_big:'״{n}״ גדול מ-100MB ולא נוסף',files_added:'{n} קבצים נוספו מוצפנים',
orig_note:'הקובץ המקורי עדיין נמצא בגלריה או בתיקייה שממנה בחרת. אם אתה רוצה שיהיה רק בכספת — מחק אותו משם ידנית. גם בצילום מתוך הכספת, יש מצלמות ששומרות עותק בגלריה — כדאי לבדוק.',
file_share:'שתף',file_download:'הורד',file_open:'פתח',download_warn:'קובץ שמורד או משותף יוצא מהכספת לא מוצפן.',file_fail:'לא הצלחתי לפתוח את הקובץ',
s_user:'שם משתמש',s_user_ph:'שם או כינוי (מופיע בגיבויים)',s_lang:'שפה',s_look:'מראה',s_theme:'ערכת צבע',s_mode:'מצב תצוגה',mode_night:'🌙 לילה',mode_day:'☀️ יום',
th_gold:'שחור וזהב',th_silver:'שחור וכסף',th_copper:'לילה ונחושת',th_jade:'ירקן',th_ruby:'בורדו',
s_security:'אבטחה',s_autolock:'נעילה אוטומטית כשיוצאים מהאפליקציה',al_0:'מיד',al_1:'אחרי דקה',al_5:'אחרי 5 דקות',al_15:'אחרי 15 דקות',
idle_note:'בנוסף, הכספת ננעלת אחרי 10 דקות בלי שימוש.',
s_clip:'ניקוי הלוח אחרי העתקה',clip_off:'כבוי',clip_s:'{n} שניות',clip_note:'הניקוי עובד כשהאפליקציה פתוחה על המסך; אחרת הוא יקרה בחזרה אליה.',
s_quick:'פתיחה מהירה',q_none:'לא מוגדרת',q_is_pin:'פעילה: קוד 6 ספרות',q_is_pattern:'פעילה: סימון על המסך',q_set_pin:'הגדר קוד',q_set_pattern:'הגדר סימון',q_remove:'בטל',
q_note:'קוד וסימון הם נוחות, לא ההגנה הראשית. אחרי 5 ניסיונות שגויים הם מתבטלים ונדרשת הסיסמה הראשית.',
q_removed:'הפתיחה המהירה בוטלה',s_bio:'טביעת אצבע',bio_set:'הפעל טביעת אצבע',bio_on:'פעילה',bio_off:'לא פעילה',bio_remove:'בטל',
bio_unsupported:'המכשיר או הדפדפן לא תומכים בטביעת אצבע מאובטחת לכספת. צריך Chrome עדכני באנדרואיד.',
bio_note:'יופיעו שתי בקשות לטביעת אצבע — אחת ליצירה ואחת לאימות. טביעת האצבע עצמה לא יוצאת מהטלפון.',
bio_ok:'טביעת האצבע הופעלה',bio_fail:'טביעת האצבע בוטלה או נכשלה',bio_removed:'טביעת האצבע בוטלה',
s_change_pw:'שנה סיסמה ראשית',cur_pw:'סיסמה נוכחית',pw_changed:'הסיסמה הראשית עודכנה',
s_new_rec:'צור קוד שחזור חדש',new_rec_c:'ייווצר קוד שחזור חדש. בכספת שבמכשיר הקוד הקודם יפסיק לעבוד, אבל גיבויים שכבר יצרת יישארו עם הקוד הקודם. להמשיך?',
s_backup:'גיבוי והעברה',b_export:'צור גיבוי מוצפן',b_import:'שחזר מגיבוי',b_last:'גיבוי אחרון: {d}',b_never:'עוד לא נוצר גיבוי',
b_hint:'תוכן הכספת בגיבוי מוצפן ונפתח רק עם הסיסמה הראשית (או קוד השחזור) שהיו בזמן יצירתו. גלויים בו רק שם המשתמש, התאריך ומספר הרשומות. בטלפון אפשר לשמור אותו ישר ל-Google Drive דרך ״שתף״.',
b_ready:'הגיבוי מוכן',b_share:'שתף (Drive, מייל…)',b_save:'שמור קובץ',b_made:'הגיבוי נשמר',
b_pw_prompt:'סיסמה ראשית של הגיבוי',b_pw_text:'הזן את הסיסמה הראשית שהייתה בזמן יצירת הגיבוי.',
b_replace:'השחזור יחליף את כל התוכן הנוכחי בכספת בתוכן הגיבוי. להמשיך?',b_restored:'הכספת שוחזרה מהגיבוי',b_bad:'הקובץ אינו גיבוי תקין של VaultNest',
b_restoring:'משחזר…',b_quick_note:'אחרי שחזור צריך להגדיר מחדש פתיחה מהירה וטביעת אצבע.',
csv_import:'ייבא סיסמאות מקובץ CSV',csv_note:'מתאים לקבצים שיוצאו מ-Chrome / Google Password Manager, Bitwarden ו-Firefox.',
csv_done:'יובאו {n} סיסמאות ({s} כפולות דולגו)',csv_delete_hint:'עכשיו מחק את קובץ ה-CSV מהמכשיר — הוא לא מוצפן.',csv_none:'לא נמצאו סיסמאות בקובץ',
csv_export:'ייצא סיסמאות ל-CSV (לא מוצפן)',csv_export_t:'ייצוא לא מוצפן',
csv_export_warn:'הקובץ יכיל את כל הסיסמאות בטקסט גלוי, וכל מי שיראה אותו יוכל לקרוא אותן. השתמש בזה רק כדי לעבור למנהל סיסמאות אחר, ומחק את הקובץ מיד אחר כך. הקלד ״{w}״ כדי להמשיך.',
export_word:'ייצא',csv_exported:'{n} סיסמאות יוצאו',
s_storage:'אחסון',st_persist_ok:'הדפדפן אישר אחסון קבוע — הוא לא ימחק את הכספת לבד כשחסר מקום.',
st_persist_no:'הדפדפן לא אישר אחסון קבוע. הוא עלול למחוק נתונים כשחסר מקום — גבה לעיתים קרובות.',st_used:'בשימוש באחסון הדפדפן: {u}',
shared_origin:'שים לב: הכספת רצה כרגע בכתובת משותפת ({h}) יחד עם אפליקציות אחרות. ניקוי נתוני אתר של אחת מהן ימחק גם את הכספת. עדיף להעביר אותה לכתובת משלה, ועד אז — לגבות.',
s_help:'עזרה',s_guide:'מדריך',s_privacy:'מדיניות פרטיות',
s_danger:'מחיקה',reset_all:'מחק את כל הכספת מהמכשיר',reset_c1:'כל הסיסמאות, הקבצים וההגדרות יימחקו מהמכשיר. אי אפשר לבטל. להמשיך?',
reset_c2:'הקלד ״{w}״ לאישור סופי',reset_word:'מחק',reset_done:'הכספת נמחקה',
ab_version:'גרסה',ab_dev:'פותח',ab_platform:'פלטפורמה',ab_storage:'אחסון',ab_storage_v:'מוצפן, על המכשיר בלבד',ab_license:'רישיון',
ab_store:'חנות AppNest',ab_share:'שתף את האפליקציה',ab_feedback:'שלח משוב',ab_security:'איך זה מאובטח',
sec_text:'לכל כספת נוצר מפתח אקראי של 256 ביט שמצפין כל פריט וכל קובץ (AES-256-GCM). המפתח עצמו נעול בסיסמה הראשית (PBKDF2-SHA256, 600,000 סבבים) ובנפרד בקוד השחזור. הסיסמה הראשית לא נשמרת בשום מקום. טביעת אצבע משתמשת במנגנון passkey של הטלפון (WebAuthn PRF). אין שרת, אין חשבון, ושום קוד לא נטען מבחוץ (ספריית QR קטנה בקוד פתוח, MIT, מוטמעת בתוך הקובץ).',
ab_disclaimer:'VaultNest מצפין את המידע במכשיר שלך, אבל האבטחה תלויה גם בסיסמה הראשית, בגיבויים ובמכשיר עצמו. מי שיש לו גישה לטלפון פתוח ולסיסמה — יכול לפתוח. אם תאבד גם את הסיסמה הראשית וגם את קוד השחזור, אין דרך לשחזר את המידע. השימוש באחריות המשתמש.',
ab_diag:'דוח אבחון',ab_diag_note:'הדוח לא כולל שום תוכן מהכספת.',
pin_enter:'הזן קוד',pin_new:'בחר קוד בן 6 ספרות',pin_again:'הזן את הקוד שוב',pin_mismatch:'הקודים לא תואמים',
pat_enter:'צייר את הסימון',pat_draw:'צייר סימון — לפחות 4 נקודות',pat_again:'צייר שוב לאישור',pat_short:'צריך לפחות 4 נקודות',pat_mismatch:'הסימונים לא תואמים',
quick_set_ok:'הפתיחה המהירה הוגדרה',quick_wrong:'שגוי. נותרו {n} ניסיונות',
quick_wiped:'יותר מדי ניסיונות שגויים. הפתיחה המהירה בוטלה — פתח עם הסיסמה הראשית.',
locked:'הכספת ננעלה',
fatal_crypto:'הדפדפן הזה לא תומך בהצפנה שהכספת צריכה. פתח אותה בכתובת https בדפדפן Chrome עדכני.',
fatal_storage:'הדפדפן חוסם אחסון מקומי (אולי גלישה בסתר). הכספת לא יכולה לשמור כאן מידע.',
fatal_file:'האפליקציה נפתחה מקובץ מקומי. פתח אותה מהכתובת באינטרנט כדי שההצפנה והשמירה יעבדו.',
err_generic:'משהו השתבש: {e}',
t_custom:'פריטים מותאמים',ts_custom:'פריט חופשי',ts_custom_d:'שם, הערות ושדות שאתה מגדיר',title_ph_custom:'למשל: ביטוח רכב',f_totp:'קוד אימות דו-שלבי (2FA)',
cf_t:'שדות נוספים',cf_label:'שם השדה',cf_value:'ערך',cf_secret:'סודי',cf_add:'הוסף שדה',
tpl_t:'התבניות שלי',tpl_d:'תבנית היא סוג פריט משלך — למשל ״ביטוח רכב״ עם שדות קבועים. היא מופיעה בתפריט ״הוסף לכספת״.',tpl_new:'תבנית חדשה',tpl_edit:'עריכת תבנית',
tpl_name:'שם התבנית',tpl_name_ph:'למשל: ביטוח רכב',tpl_icon:'סמל',tpl_fields:'השדות בתבנית',tpl_del_c:'למחוק את התבנית ״{n}״? פריטים שכבר נוצרו ממנה יישארו.',tpl_mine:'תבנית שלי',s_items:'פריטים',
totp_scan:'סרוק QR',totp_scan_img:'מצילום מסך',totp_note:'הקוד מתחלף כל 30 שניות. שים לב: כשהסיסמה והקוד שמורים באותה כספת, זה כבר לא באמת ״שני גורמים״.',
totp_noqr:'לא נמצא קוד QR בתמונה',totp_bad:'מפתח 2FA לא תקין',totp_migration:'זה קוד ייצוא של Google Authenticator (כמה חשבונות יחד). צריך לסרוק את ה-QR המקורי של כל אתר, או להקליד את המפתח.',
totp_ok:'המפתח נקלט',totp_nodetector:'סריקת QR לא נתמכת בדפדפן הזה — הקלד את המפתח ידנית (מופיע באתר תחת ״לא מצליח לסרוק?״).',
scan_t:'סריקת מסמך',scan_hint:'גרור את ארבע הפינות לקצוות המסמך.',scan_rotate:'סובב',scan_full:'כל התמונה',scan_crop:'ישר וחתוך',scan_doc:'מסמך',scan_gray:'אפור',scan_orig:'מקור',
scan_btn:'סרוק מסמך',scan_saved:'המסמך נסרק ונשמר מוצפן',att_t:'קבצים מצורפים',att_empty:'אפשר לצרף לפריט צילום, סריקה או קובץ — למשל חזית וגב של כרטיס.',
sh_t:'שיתוף מאובטח',sh_intro:'ייווצר קובץ מוצפן עם הפריט הזה (וקבצים מצורפים עד 25MB), וקוד שרק איתו אפשר לפתוח אותו. מי שמקבל צריך גם הוא את VaultNest.',
sh_code_is:'זה הקוד לפתיחת הקובץ:',sh_skipped:'{n} קבצים גדולים מדי לא נכללו',sh_how:'שלח את הקובץ ואת הקוד בשני ערוצים שונים — למשל את הקובץ במייל ואת הקוד בהודעה או בטלפון.',
sh_send_file:'שלח את הקובץ',sh_copy_code:'העתק קוד',sh_code_prompt:'קוד הפתיחה',sh_code_text:'הזן את הקוד שקיבלת מהשולח.',sh_wrong:'הקוד שגוי',
sh_confirm:'לשמור בכספת את ״{n}״ ({f} קבצים מצורפים)?',sh_recv_t:'קבל פריט משותף',sh_recv_d:'פתיחת קובץ שיתוף מוצפן',sh_saved:'הפריט נשמר בכספת',sh_bad:'זה לא קובץ שיתוף של VaultNest',
sh_need_unlock:'קודם צור או פתח כספת, ואז פתח את קובץ השיתוף',


kit_t:'ערכת חירום להדפסה',kit_d:'דף אחד עם כתובת האפליקציה, קוד השחזור והוראות — לשמור עם המסמכים החשובים בבית או לתת לבן משפחה שאתה סומך עליו.',
kit_new:'צור קוד שחזור חדש והדפס אותו',kit_blank:'הדפס עם מקום לכתוב את הקוד ביד',kit_new_note:'קוד חדש מחליף את הקוד הקודם בכספת שבמכשיר. גיבויים שכבר יצרת עדיין נפתחים רק עם הקוד הקודם — לכן מיד אחר כך תתבקש ליצור גיבוי חדש.',
kit_addr:'כתובת האפליקציה',kit_code_note:'הקוד פותח את הכספת במקום הסיסמה הראשית. מי שמחזיק בדף הזה ובקובץ הגיבוי — יכול לפתוח אותה.',kit_backup_where:'איפה שמור קובץ הגיבוי',
kit_steps_t:'איך משחזרים',kit_s1:'פותחים את כתובת האפליקציה בדפדפן Chrome.',kit_s2:'במסך הפתיחה לוחצים ״יש לי כבר גיבוי — שחזר ממנו״ ובוחרים את קובץ הגיבוי.',
kit_s3:'מזינים את הסיסמה הראשית — או את קוד השחזור מהדף הזה.',kit_s4:'אם נפתח עם קוד השחזור: בהגדרות בוחרים סיסמה ראשית חדשה.',kit_warn:'שמור את הדף במקום בטוח ולא ליד הטלפון.',
kit_after:'אם ההדפסה לא הצליחה — זה הקוד החדש. בכספת שבמכשיר הקוד הקודם כבר לא עובד; גיבויים ישנים עדיין צריכים את הקוד הקודם.',
cal_t:'תזכורת ביומן',cal_title:'{n}: התוקף פג ב-{d}',cal_details:'תזכורת מ-VaultNest לחדש לפני שפג התוקף.',cal_when:'האירוע ייקבע ל-{d}, 30 יום לפני התוקף',
cal_privacy:'מה שכתוב בכותרת עובר ל-Google או לקובץ היומן. אל תכתוב בה מספר מסמך או פרט סודי.',cal_google:'הוסף ל-Google Calendar',cal_ics:'קובץ יומן (לכל יומן אחר)',
wifi_qr:'QR להתחברות',wifi_qr_d:'אורח סורק במצלמה ומתחבר לרשת. מי שסורק מקבל את הסיסמה.',
hist_t:'היסטוריית סיסמאות',hist_d:'ערכים קודמים שהוחלפו בפריט הזה (עד 15).',hist_clear:'נקה היסטוריה',hist_clear_c:'למחוק את כל הערכים הקודמים של הפריט הזה?',
gen_chars:'תווים',gen_words:'מילים',gen_wcount:'מספר מילים: {n}',gen_wlang:'שפת המילים',gen_sep:'מפריד',gen_space:'רווח',gen_cap:'אות גדולה בתחילת כל מילה',gen_num:'הוסף ספרה',
gen_words_note:'משפט-סיסמה מכמה מילים אקראיות קל יותר להקליד ולזכור, ועדיין חזק. מילים בעברית מתאימות רק לאתרים שמקבלים עברית בסיסמה.',
gen_default_note:'ההגדרות כאן משמשות גם את כפתור ״צור סיסמה״ בחלון העריכה.',






b_checking:'בודק את כל הגיבוי לפני שמשנים משהו…',
b_corrupt:'הגיבוי פגום: {n} רשומות בו לא נפתחות. כדי לא לאבד מידע, השחזור בוטל — הכספת הנוכחית לא שונתה. נסה קובץ גיבוי אחר.',
b_summary:'הגיבוי נבדק ותקין: {i} פריטים ו-{f} קבצים, מתאריך {d}.',
b_unknown:'{n} רשומות בגיבוי שייכות לכספת ההסוואה הישנה; הן יישמרו כמו שהן.',
b_replace_cur:'השחזור יחליף את הכספת הנוכחית ({i} פריטים, {f} קבצים) בתוכן הגיבוי.',
b_backup_first:'קודם גבה את הכספת הנוכחית',
b_verify_fail:'השחזור נכתב אבל הבדיקה החוזרת לא תאמה. אל תמחק את קובץ הגיבוי — פתח את הכספת ובדוק.',
b_restore_fail:'השחזור נכשל והבוטל לגמרי — הכספת הנוכחית לא שונתה.',
keys_backup_now:'גיבויים ישנים נפתחים רק עם הסיסמה או קוד השחזור הקודמים. צור עכשיו גיבוי חדש שמתאים לפרטים החדשים, ושמור אותו במקום הקודם.',
backup_keys:'החלפת סיסמה או קוד שחזור מאז הגיבוי האחרון. צור גיבוי חדש שמתאים להם.',
kit_match:'הקוד מתאים לגיבויים שנוצרו מ-{d} והלאה. גיבויים ישנים יותר נפתחים רק עם הקוד הקודם.',
scan_badquad:'הפינות לא יוצרות צורה תקינה. גרור אותן לארבע הפינות של המסמך.',
exp_bad:'תוקף לא תקין — כתוב חודש (01–12) ושנה, למשל 08/27',
pw_space:'יש רווח בהתחלה או בסוף',
cal_title_card:'לחדש כרטיס אשראי — התוקף פג ב-{d}',
cal_title_doc:'לחדש מסמך — התוקף פג ב-{d}',
cal_title_lbl:'כותרת האירוע',
cal_when_soon:'התוקף קרוב, לכן האירוע ייקבע למחר ({d})',
dcl_t:'מחק את כספת ההסוואה הישנה',
dcl_d:'הזן את סיסמת ההסוואה. יימחקו רק רשומות שנפתחות איתה — שום רשומה אחרת לא תיגע.',
dcl_done:'נמחקו {i} פריטים ו-{f} קבצים של כספת ההסוואה',
dcl_note:'כספת ההסוואה הוסרה מהאפליקציה כי אי אפשר להבטיח הסוואה אמיתית בדפדפן. אם יצרת כזו, אפשר למחוק את התוכן שלה כאן.',
unreadable:'{n} רשומות לא נפתחות עם המפתח של הכספת (ייתכן שנפגמו). הן לא נמחקו. שמור את קבצי הגיבוי שלך ופנה לתמיכה.',
reset_blocked:'הדפדפן לא השלים את המחיקה — כנראה האפליקציה פתוחה בלשונית או חלון נוסף. סגור אותם ונסה שוב.',
more_t:'עוד פעולות',
att_add:'צרף קובץ',
att_existing:'קובץ שכבר בכספת',
att_existing_d:'בחר קבצים מהכספת שיצורפו לפריט הזה. קובץ שמצורף לפריט אחר יעבור לכאן.',
att_none_free:'אין עוד קבצים בכספת לצרף',
att_do:'צרף',
att_done:'{n} קבצים צורפו',
in_t:'שיתופים לכספת',
in_dead:'{n} שיתופים לא ניתנים לפתיחה — הם נוצרו לפני שחזור או החלפת כספת, ולכן המפתח שלהם כבר לא קיים. הם נמחקו.',
in_files_t:'{n} קבצים שותפו לכספת',
in_skipped:'{n} קבצים לא נקלטו (יותר מ-20 קבצים או מעל 100MB בסך הכול)',
in_attach:'מצורף לפריט',
in_attach_none:'— לא מצורף לפריט —',
in_save:'הצפן ושמור בכספת',
in_later:'אחר כך',
in_discard:'מחק את השיתוף',
in_discard_c:'למחוק את השיתוף בלי לשמור אותו בכספת?',
in_orig:'הקובץ המקורי עדיין אצלך בגלריה — מחק אותו משם אם צריך.',
in_text_t:'טקסט ששותף',
in_found:'נמצאו {n} פריטים לאתר הזה',
in_no_match:'אין עדיין סיסמה לאתר הזה',
in_new_login:'צור סיסמה לאתר הזה',
in_as_note:'שמור כפתק מאובטח',
in_pending:'יש {n} שיתופים שממתינים לטיפול',
in_handle:'טפל עכשיו',
in_nokey:'כדי לשתף לכספת, פתח אותה פעם אחת אחרי העדכון ואז שתף שוב. שום דבר לא נשמר.',
in_err:'השיתוף נכשל ולא נשמר. נסה שוב.',
in_arrived:'השיתוף התקבל מוצפן — פתח את הכספת כדי לשמור אותו.'
},
en:{
app_sub:'My vault',skip_link:'Skip to content',
lock_title:'Vault locked',master_pw:'Master password',unlock:'Unlock',unlocking:'Unlocking…',wrong_pw:'Wrong password',
wait_s:'Too many attempts. Try again in {s} seconds',use_bio:'Fingerprint',use_pin:'PIN',use_pattern:'Pattern',
forgot:'I forgot my password',rec_enter:'Enter your recovery code',rec_wrong:'Wrong recovery code',rec_ok_set_new:'Code accepted. Choose a new master password',
back:'Back',cancel:'Cancel',save:'Save',delete:'Delete',edit:'Edit',close:'Close',copy:'Copy',copied:'Copied',show:'Show',hide:'Hide',
open:'Open',done:'Done',next:'Next',skip:'Skip',confirm:'Confirm',later:'Later',continue:'Continue',
ob1_t:'Welcome to your vault',ob1_d:'One place for passwords, credit cards, codes, documents and important photos.',
ob2_t:'Encrypted, and it stays with you',ob2_d:'Everything is encrypted with AES-256 before it is saved, and stays on this device only. Nothing is sent to a server.',
ob3_t:'One master password',ob3_d:'It unlocks everything else, and there is no way for us to recover it. That is why you also get a recovery code — write it down on paper.',
ob4_t:'Quick unlock',ob4_d:'After setup you can unlock with your fingerprint, a PIN or a screen pattern.',
ob5_t:'Backups are your insurance',ob5_d:'If the phone is lost or browser data is cleared, only a backup file brings your data back. The backup content is encrypted.',
ob_start:"Let's start",
create_t:'Create a master password',create_d:'At least 10 characters. A short sentence you remember beats a complicated word.',
new_pw:'New master password',pw_confirm:'Type it again',pw_mismatch:"Passwords don't match",pw_short:'At least 10 characters',
pw_weak_warn:'This password is weak, and all of the vault security relies on it. Continue anyway?',create_btn:'Create the vault',creating:'Creating and encrypting…',
restore_existing:'I already have a backup — restore it',
str_0:'Very weak',str_1:'Weak',str_2:'Fair',str_3:'Strong',str_4:'Very strong',
rec_t:'Your recovery code',rec_d:'This is the only code that opens the vault if you forget the master password. Write it on paper and keep it somewhere safe — not on the phone. It will not be shown again.',
rec_check:'I wrote the code down somewhere safe',rec_copy:'Copy code',
quick_offer_t:'Add quick unlock?',quick_offer_d:'So you do not have to type the master password every time. You can change this anytime in Settings.',
search_ph:'Search the vault…',cat_all:'All',cat_fav:'Favorites',files:'Files & photos',
t_login:'Passwords & sites',t_card:'Credit cards',t_code:'Codes',t_wifi:'Wi-Fi networks',t_bank:'Bank accounts',t_identity:'ID documents',t_note:'Secure notes',
ts_login:'Website or app login',ts_card:'Credit card',ts_code:'Code (alarm, door, safe…)',ts_wifi:'Wi-Fi network',ts_bank:'Bank account',ts_identity:'ID document',ts_note:'Secure note',
add_item:'Add to vault',add_what:'What would you like to add?',add_files:'Files or photos',
gen_t:'Password generator',health_t:'Password health',settings:'Settings',about:'About',lock_now:'Lock now',
items_n:'{n} items',
backup_nag:'{d} days since your last backup.',backup_never:'You have no backup yet. Without one, clearing browser data deletes the vault.',backup_now:'Back up now',
empty_list:'Nothing here yet. Tap "Add to vault" to start.',no_results:'No items found',
trash:'Trash',trash_empty:'Trash is empty',trash_note:'Items here are permanently deleted after 30 days.',restore:'Restore',delete_forever:'Delete forever',
moved_trash:'Moved to trash',restored:'Restored',empty_trash:'Empty trash',empty_trash_c:'Permanently delete everything in the trash? This cannot be undone.',
f_title:'Name',f_username:'Username / email',f_password:'Password',f_url:'Website address',f_notes:'Notes',f_cardholder:'Cardholder name',
f_number:'Card number',f_expiry:'Expiry',f_cvv:'CVV (3 digits on the back)',f_cardPin:'PIN',f_issuer:'Card company / bank',f_code:'Code',
f_ssid:'Network name',f_security:'Security type',sec_none:'Open (no password)',f_bankName:'Bank',f_branch:'Branch',f_account:'Account number',
f_docType:'Document type',f_fullName:'Full name',f_docNumber:'Document number',f_issued:'Issue date',f_docExpiry:'Expiry date',f_fav:'Mark as favorite',
title_ph_login:'e.g. Gmail, my bank, Netflix',title_ph_card:'e.g. Visa',title_ph_code:'e.g. Home alarm',title_ph_wifi:'e.g. Home network',
title_ph_bank:'e.g. Checking account',title_ph_identity:'e.g. Passport',title_ph_note:'e.g. Google backup codes',
new_item:'New item',edit_item:'Edit',need_title:'Give the item a name',saved:'Saved',save_fail:'Save failed: {e}',
del_confirm:'Move "{n}" to the trash?',del_forever_c:'Delete forever? This cannot be undone.',
open_site:'Open website',created_at:'Created {d}',updated_at:'Updated {d}',fav_on:'Added to favorites',fav_off:'Removed from favorites',
reused_n:'Used in {n} items',old_pw:'Not changed for over a year',
check_breach:'Check for leaks',breach_t:'Leak check',
breach_consent:'The check sends Have I Been Pwned only 5 characters of an encrypted "fingerprint" (hash) of the password — never the password itself or any other detail. Continue?',
breach_found:'Found {n} times in known leaks — change it',breach_clean:'Not found in known leaks',breach_err:'The check failed. Are you online?',checking:'Checking…',
exp_soon:'Expires in {d} days',exp_past:'Expired',
gen_length:'Length: {n}',gen_lower:'Lowercase (a-z)',gen_upper:'Uppercase (A-Z)',gen_digits:'Digits (0-9)',gen_symbols:'Symbols (!@#)',
gen_ambig:'No look-alikes (O/0, l/1)',gen_new:'Generate',bits:'Estimated strength: {b} bits',
h_score:'Vault score',h_weak:'Weak passwords',h_reused:'Reused passwords',h_old:'Not changed for over a year',h_expiring:'Cards and documents expired or expiring soon',
h_breached:'Passwords found in leaks',h_all_good:'No problems here',h_checkall:'Check all passwords for leaks',h_checking:'Checking {i} of {n}…',
h_none:'No passwords to check yet.',h_note:'Strength is an estimate based on length and character variety — not a guarantee.',
files_add:'Add files',files_camera:'Take photo',file_cat:'Category',file_name:'File name',
fc_all:'All',fc_id:'IDs',fc_money:'Money',fc_home:'Home',fc_car:'Car',fc_health:'Health',fc_other:'Other',
files_empty:'No files yet. Add photos, PDFs or any other file — they are encrypted before saving.',
encrypting:'Encrypting {i} of {n}…',file_big:'"{n}" is larger than 100MB and was not added',files_added:'{n} files added, encrypted',
orig_note:'The original file is still in your gallery or the folder you picked it from. If you want it only in the vault, delete it there yourself. Even for photos taken from inside the vault, some camera apps keep a copy in the gallery — worth checking.',
file_share:'Share',file_download:'Download',file_open:'Open',download_warn:'A downloaded or shared file leaves the vault unencrypted.',file_fail:'Could not open the file',
s_user:'User name',s_user_ph:'Name or nickname (shown on backups)',s_lang:'Language',s_look:'Appearance',s_theme:'Color theme',s_mode:'Display mode',mode_night:'🌙 Night',mode_day:'☀️ Day',
th_gold:'Black & gold',th_silver:'Black & silver',th_copper:'Night & copper',th_jade:'Jade',th_ruby:'Burgundy',
s_security:'Security',s_autolock:'Auto-lock when leaving the app',al_0:'Immediately',al_1:'After 1 minute',al_5:'After 5 minutes',al_15:'After 15 minutes',
idle_note:'The vault also locks after 10 minutes without use.',
s_clip:'Clear clipboard after copying',clip_off:'Off',clip_s:'{n} seconds',clip_note:'Clearing works while the app is on screen; otherwise it happens when you return to it.',
s_quick:'Quick unlock',q_none:'Not set',q_is_pin:'On: 6-digit PIN',q_is_pattern:'On: screen pattern',q_set_pin:'Set PIN',q_set_pattern:'Set pattern',q_remove:'Turn off',
q_note:'PIN and pattern are for convenience, not the main protection. After 5 wrong tries they are turned off and the master password is required.',
q_removed:'Quick unlock turned off',s_bio:'Fingerprint',bio_set:'Turn on fingerprint',bio_on:'On',bio_off:'Off',bio_remove:'Turn off',
bio_unsupported:'This device or browser does not support secure fingerprint unlock for the vault. An up-to-date Chrome on Android is needed.',
bio_note:'You will be asked for your fingerprint twice — once to create, once to verify. Your fingerprint never leaves the phone.',
bio_ok:'Fingerprint unlock is on',bio_fail:'Fingerprint was cancelled or failed',bio_removed:'Fingerprint unlock turned off',
s_change_pw:'Change master password',cur_pw:'Current password',pw_changed:'Master password updated',
s_new_rec:'Create a new recovery code',new_rec_c:'A new recovery code will be created. On this device the previous code stops working, but backups you already made keep the previous code. Continue?',
s_backup:'Backup & transfer',b_export:'Create encrypted backup',b_import:'Restore from backup',b_last:'Last backup: {d}',b_never:'No backup yet',
b_hint:'The vault content in the backup is encrypted and opens only with the master password (or recovery code) set when it was made. Only the user name, date and record counts are visible. On a phone you can save it straight to Google Drive with "Share".',
b_ready:'Backup ready',b_share:'Share (Drive, email…)',b_save:'Save file',b_made:'Backup saved',
b_pw_prompt:'Backup master password',b_pw_text:'Enter the master password that was set when this backup was made.',
b_replace:'Restoring replaces everything in the vault with the backup contents. Continue?',b_restored:'Vault restored from backup',b_bad:'This file is not a valid VaultNest backup',
b_restoring:'Restoring…',b_quick_note:'After restoring, set up quick unlock and fingerprint again.',
csv_import:'Import passwords from a CSV file',csv_note:'Works with exports from Chrome / Google Password Manager, Bitwarden and Firefox.',
csv_done:'Imported {n} passwords ({s} duplicates skipped)',csv_delete_hint:'Now delete the CSV file from your device — it is not encrypted.',csv_none:'No passwords found in the file',
csv_export:'Export passwords to CSV (unencrypted)',csv_export_t:'Unencrypted export',
csv_export_warn:'The file will contain every password in plain text, readable by anyone who sees it. Use this only to move to another password manager, and delete the file right after. Type "{w}" to continue.',
export_word:'EXPORT',csv_exported:'{n} passwords exported',
s_storage:'Storage',st_persist_ok:'The browser granted persistent storage — it will not delete the vault on its own when space runs low.',
st_persist_no:'The browser did not grant persistent storage. It may delete data when space runs low — back up often.',st_used:'Browser storage in use: {u}',
shared_origin:'Note: the vault currently runs on a shared address ({h}) with other apps. Clearing site data for any of them also deletes the vault. Move it to its own address, and until then — back up.',
s_help:'Help',s_guide:'Guide',s_privacy:'Privacy policy',
s_danger:'Delete',reset_all:'Delete the whole vault from this device',reset_c1:'All passwords, files and settings will be deleted from this device. This cannot be undone. Continue?',
reset_c2:'Type "{w}" to confirm',reset_word:'DELETE',reset_done:'Vault deleted',
ab_version:'Version',ab_dev:'Developer',ab_platform:'Platform',ab_storage:'Storage',ab_storage_v:'Encrypted, on this device only',ab_license:'License',
ab_store:'AppNest store',ab_share:'Share the app',ab_feedback:'Send feedback',ab_security:'How it is secured',
sec_text:'Each vault gets a random 256-bit key that encrypts every item and file (AES-256-GCM). That key is locked with your master password (PBKDF2-SHA256, 600,000 rounds) and separately with the recovery code. The master password is never stored. Fingerprint unlock uses the phone passkey system (WebAuthn PRF). No server, no account, and nothing is loaded from outside (a small open-source MIT QR library is embedded in the file).',
ab_disclaimer:'VaultNest encrypts your data on your device, but security also depends on your master password, your backups and the device itself. Anyone with your unlocked phone and password can open it. If you lose both the master password and the recovery code, the data cannot be recovered. Use at your own responsibility.',
ab_diag:'Diagnostic report',ab_diag_note:'The report contains no vault content.',
pin_enter:'Enter PIN',pin_new:'Choose a 6-digit PIN',pin_again:'Enter the PIN again',pin_mismatch:"PINs don't match",
pat_enter:'Draw your pattern',pat_draw:'Draw a pattern — at least 4 dots',pat_again:'Draw it again to confirm',pat_short:'At least 4 dots are needed',pat_mismatch:"Patterns don't match",
quick_set_ok:'Quick unlock is set',quick_wrong:'Wrong. {n} tries left',
quick_wiped:'Too many wrong tries. Quick unlock was turned off — unlock with the master password.',
locked:'Vault locked',
fatal_crypto:'This browser does not support the encryption the vault needs. Open it over https in an up-to-date Chrome.',
fatal_storage:'The browser blocks local storage (maybe private browsing). The vault cannot save data here.',
fatal_file:'The app was opened from a local file. Open it from its web address so encryption and saving work.',
err_generic:'Something went wrong: {e}',
t_custom:'Custom items',ts_custom:'Free-form item',ts_custom_d:'Name, notes and fields you define',title_ph_custom:'e.g. Car insurance',f_totp:'Two-factor code (2FA)',
cf_t:'Extra fields',cf_label:'Field name',cf_value:'Value',cf_secret:'Secret',cf_add:'Add field',
tpl_t:'My templates',tpl_d:'A template is your own item type — e.g. "Car insurance" with fixed fields. It shows up in the "Add to vault" menu.',tpl_new:'New template',tpl_edit:'Edit template',
tpl_name:'Template name',tpl_name_ph:'e.g. Car insurance',tpl_icon:'Icon',tpl_fields:'Template fields',tpl_del_c:'Delete the template "{n}"? Items already made from it stay.',tpl_mine:'My template',s_items:'Items',
totp_scan:'Scan QR',totp_scan_img:'From screenshot',totp_note:'The code changes every 30 seconds. Note: with the password and the code in the same vault, it is no longer truly "two factors".',
totp_noqr:'No QR code found in the image',totp_bad:'Invalid 2FA key',totp_migration:'This is a Google Authenticator export code (several accounts at once). Scan each site\'s original QR, or type the key.',
totp_ok:'Key captured',totp_nodetector:'QR scanning is not supported in this browser — type the key manually (sites show it under "Can\'t scan?").',
scan_t:'Scan document',scan_hint:'Drag the four corners to the edges of the document.',scan_rotate:'Rotate',scan_full:'Whole image',scan_crop:'Straighten & crop',scan_doc:'Document',scan_gray:'Gray',scan_orig:'Original',
scan_btn:'Scan document',scan_saved:'Document scanned and saved, encrypted',att_t:'Attachments',att_empty:'Attach a photo, scan or file to this item — e.g. the front and back of a card.',
sh_t:'Secure share',sh_intro:'An encrypted file will be created with this item (and attachments up to 25MB), plus a code that is the only way to open it. The recipient also needs VaultNest.',
sh_code_is:'This is the code that opens the file:',sh_skipped:'{n} files were too large and were left out',sh_how:'Send the file and the code through two different channels — for example the file by email and the code by message or phone.',
sh_send_file:'Send the file',sh_copy_code:'Copy code',sh_code_prompt:'Opening code',sh_code_text:'Enter the code you got from the sender.',sh_wrong:'Wrong code',
sh_confirm:'Save "{n}" ({f} attachments) in the vault?',sh_recv_t:'Receive a shared item',sh_recv_d:'Open an encrypted share file',sh_saved:'Item saved in the vault',sh_bad:'This is not a VaultNest share file',
sh_need_unlock:'First create or unlock a vault, then open the share file',


kit_t:'Printable emergency kit',kit_d:'One page with the app address, your recovery code and instructions — keep it with your important papers at home, or give it to a family member you trust.',
kit_new:'Create a new recovery code and print it',kit_blank:'Print with space to write the code by hand',kit_new_note:'A new code replaces the previous one in the vault on this device. Backups you already made still open only with the previous code — so you will be asked to create a new backup right after.',
kit_addr:'App address',kit_code_note:'This code opens the vault instead of the master password. Anyone holding this page and the backup file can open it.',kit_backup_where:'Where the backup file is kept',
kit_steps_t:'How to restore',kit_s1:'Open the app address in Chrome.',kit_s2:'On the first screen tap "I already have a backup — restore it" and pick the backup file.',
kit_s3:'Enter the master password — or the recovery code from this page.',kit_s4:'If you opened it with the recovery code: choose a new master password in Settings.',kit_warn:'Keep this page somewhere safe, not next to the phone.',
kit_after:'If printing did not work — this is the new code. On this device the previous code no longer works; older backups still need the previous code.',
cal_t:'Calendar reminder',cal_title:'{n}: expires on {d}',cal_details:'Reminder from VaultNest to renew before it expires.',cal_when:'The event will be set for {d}, 30 days before expiry',
cal_privacy:'Whatever is in the title goes to Google or to the calendar file. Do not put a document number or secret detail in it.',cal_google:'Add to Google Calendar',cal_ics:'Calendar file (for any other calendar)',
wifi_qr:'QR to connect',wifi_qr_d:'A guest scans it with the camera and joins the network. Whoever scans it gets the password.',
hist_t:'Password history',hist_d:'Previous values replaced in this item (up to 15).',hist_clear:'Clear history',hist_clear_c:'Delete all previous values of this item?',
gen_chars:'Characters',gen_words:'Words',gen_wcount:'Number of words: {n}',gen_wlang:'Word language',gen_sep:'Separator',gen_space:'Space',gen_cap:'Capitalize each word',gen_num:'Add a digit',
gen_words_note:'A passphrase of random words is easier to type and remember, and still strong. Hebrew words only suit sites that accept Hebrew in passwords.',
gen_default_note:'These settings are also used by the "Generate" button in the edit window.',





b_checking:'Checking the whole backup before changing anything…',
b_corrupt:'The backup is damaged: {n} records in it do not open. To avoid losing data, the restore was cancelled — your current vault was not changed. Try another backup file.',
b_summary:'The backup checked out: {i} items and {f} files, from {d}.',
b_unknown:'{n} records in the backup belong to the old decoy vault; they will be kept as they are.',
b_replace_cur:'Restoring will replace the current vault ({i} items, {f} files) with the backup contents.',
b_backup_first:'Back up the current vault first',
b_verify_fail:'The restore was written but the read-back check did not match. Do not delete the backup file — open the vault and check.',
b_restore_fail:'The restore failed and was fully cancelled — your current vault was not changed.',
keys_backup_now:'Old backups open only with the previous password or recovery code. Create a new backup that matches the new details now, and keep it where you kept the old one.',
backup_keys:'You changed the password or recovery code since the last backup. Create a new backup that matches them.',
kit_match:'This code matches backups created from {d} on. Older backups open only with the previous code.',
scan_badquad:'The corners do not form a valid shape. Drag them to the four corners of the document.',
exp_bad:'Invalid expiry — enter month (01–12) and year, e.g. 08/27',
pw_space:'Has a space at the start or end',
cal_title_card:'Renew credit card — expires on {d}',
cal_title_doc:'Renew document — expires on {d}',
cal_title_lbl:'Event title',
cal_when_soon:'Expiry is close, so the event will be set for tomorrow ({d})',
dcl_t:'Delete the old decoy vault',
dcl_d:'Enter the decoy password. Only records that open with it will be deleted — no other record is touched.',
dcl_done:'Deleted {i} items and {f} files of the decoy vault',
dcl_note:'The decoy vault was removed from the app because real hiding cannot be guaranteed in a browser. If you created one, you can delete its contents here.',
unreadable:'{n} records do not open with the vault key (they may be damaged). They were not deleted. Keep your backup files and contact support.',
reset_blocked:'The browser did not finish deleting — the app is probably open in another tab or window. Close it and try again.',
more_t:'More actions',
att_add:'Attach a file',
att_existing:'A file already in the vault',
att_existing_d:'Pick files from the vault to attach to this item. A file attached to another item moves here.',
att_none_free:'No other files in the vault to attach',
att_do:'Attach',
att_done:'{n} files attached',
in_t:'Shares to the vault',
in_dead:'{n} shares cannot be opened — they were made before a restore or vault change, so their key no longer exists. They were deleted.',
in_files_t:'{n} files shared to the vault',
in_skipped:'{n} files were not received (more than 20 files or over 100MB in total)',
in_attach:'Attached to item',
in_attach_none:'— not attached —',
in_save:'Encrypt & save in the vault',
in_later:'Later',
in_discard:'Discard the share',
in_discard_c:'Discard the share without saving it in the vault?',
in_orig:'The original is still in your gallery — delete it there if needed.',
in_text_t:'Shared text',
in_found:'{n} items found for this site',
in_no_match:'No password for this site yet',
in_new_login:'Create a password for this site',
in_as_note:'Save as a secure note',
in_pending:'{n} shares are waiting',
in_handle:'Handle now',
in_nokey:'To share into the vault, open it once after the update and then share again. Nothing was saved.',
in_err:'The share failed and was not saved. Try again.',
in_arrived:'The share arrived encrypted — unlock the vault to save it.'
}};
let CUR='he';
function T(k,v){const L=LANG[CUR]||LANG.en;let s=L[k]!=null?L[k]:(LANG.en[k]!=null?LANG.en[k]:k);if(v)s=s.replace(/\{(\w+)\}/g,(m,n)=>v[n]!=null?v[n]:m);return s;}
/* passphrase word lists (own, simple common words) */
const WORDS={en:'able acid acorn actor adapt admit adult agent agree ahead aim air alarm album alert alien alley alpha amber amigo anchor angle ankle apple april apron arch arena argue arm army arrow art aside atlas atom attic audio aunt autumn avoid awake award axis baby bacon badge bagel baker bald ball bamboo banana band bank barn barrel basil basket bath beach beam bean bear beard beast bed bee beef bell belt bench berry bike bird bishop black blade blank blast blend blink block bloom blue board boat body bold bolt bonus book boot boss bottle bounce bowl box brain brave bread brick bride brief brisk broom brown brush bubble bucket budget buddy bulb bunny burger bus butter button buzz cabin cable cactus cake calm camel camera camp canal candy canoe canvas canyon cape card cargo carpet carrot cart castle cat cave cedar cello chain chair chalk champ charm cheek cheese cherry chess chief chip choir cider cigar circle city civic clam clap claw clay clean clerk cliff climb clock cloud clown club coach coast cobra cocoa coin comet coral corn cotton couch cousin crab craft crane crate crisp crow crown cube cup curry curve cycle daisy dance dawn deer delta denim depth desert desk dial diary diesel dime diner dingo disco dish diver dizzy dock doll dolphin donkey door dough dove dragon drama dream dress drift drill drum duck dune dust eagle earth easel echo edge eel eight elbow elder elm ember empty engine enjoy epic equal error essay event exact exit extra fable fabric fairy faith falcon fancy farm fawn feast feather fence ferry fever fiber fiddle field fifty film final finch fire fish flag flame flash flint float flock flour flute foam focus fog folk forest fork fort fossil fox frame fresh frog frost fruit fudge fuel fuzzy gadget galaxy game garden garlic gate gecko gem genie ghost giant gift ginger giraffe glass globe glove glow goat gold golf goose gorilla grain grape grass gravy green grid grill grin group guitar gull habit hammer hand happy harbor harp hat hawk hazel heart hedge helmet hero hill hippo hobby honey hood hook horse hotel house humor hunter husky ice icon idea igloo image index ink input iris iron island ivory jacket jaguar jam jar jazz jeans jelly jet jewel jog joke judge juice jumbo jungle kayak kettle key kid king kite kitten kiwi knee knife koala label ladder lake lamp lane laser latte lava lawn layer leaf lemon lens lever lily lime linen lion liquid lobby lock lodge logic lotus lucky lunar lunch lynx magic magnet mango maple marble market mask meadow medal melon memo mercy metal meteor mint mirror mist mixer model monk moose motor mouse mud mug muffin museum music nacho napkin navy nest net night ninja noble noodle north novel nut oak oasis ocean olive omega onion opera orange orbit orchid otter oven owl oyster paddle page palm panda paper parade park parrot pasta patch peach peanut pearl pebble pedal pencil pepper piano pickle pig pillow pilot pine pink pizza planet plum poem polar pony pool poppy potato pretty prism pulse pumpkin puppy puzzle quail quartz queen quest quick quiet quilt quiz rabbit radar radio rain ranch raven razor recipe reef relax rhino ribbon rice ridge river robin robot rocket rodeo roof rose royal ruby rugby salad salmon salsa sand satin sauce scarf school scout sea seal seed shark sheep shelf shell ship shoe silk silver singer siren skate sketch ski sky sleep slide smile snail snake snow soap sock sofa solar song soup spark spice spider spoon spring squid stamp star steam stone storm straw sugar summer sun surf swan sweet swing table taco tango tea teddy tent tiger toast tomato topaz torch tower toy tractor train tree trick tulip tuna tunnel turtle twin umbrella uncle unit urban valley vanilla velvet violin visit vivid volcano wafer wagon walnut walrus water wave wheel whale window winter wizard wolf wood wool yacht yak yard yellow yoga zebra zero zigzag zone'.split(' '),he:'אבן אגם אגוז אדמה אוהל אוזן אוצר אורז אות אחות איש אלון אמא אננס אסם אפרסק ארגז ארון אריה ארמון אש באר בגד בובה בוקר בטן ביצה בית בלון במה בננה בקבוק ברווז ברז ברק גבינה גבעה גדר גוזל גזר גחלת גינה גיטרה גלגל גמל גן גשם גשר דבורה דבש דג דגל דוב דודה דלת דף דרך הר הרים ורד זאב זברה זהב זית זמר זנב זרע חבל חבר חג חול חולצה חום חוף חורף חותם חזיר חיוך חלב חלון חלום חמור חסה חתול טווס טוסט טיל טלה טנא טרקטור יד ילד ים ינשוף יער ירח ירוק כדור כוכב כוס כותרת כיסא כלב כנף כפית כפר כרוב כתר לב לביא לחם לילה לימון לוח לטאה מגדל מדבר מזלג מחברת מטוס מטרייה מים מכונית מלון מלך מנגו מנורה מסגרת מעיל מפה מפתח מראה מרק משחק מתנה נבל נהר נוצה נחל נחש נמל נמר נסיך נעל נר סבא סבון סוס סוכר סולם סוסון סיר סלע סנאי ספר ספינה עגבניה עגלה עוגה עוף עט עין עיר עכבר ענן עפרון עץ פגז פונפון פיל פינה פירה פנס פסל פעמון פרה פרח פרפר צב צבע צדף צלחת צנון צפרדע קוף קיץ קיר קמח קן קנה קסם קערה קפה קקטוס קרח קשת ראש רגל רדיו רוח רחוב ריבה רימון רכבת רעם שבלול שדה שוקו שולחן שועל שורש שחף שטיח שיר שלג שמיים שמש שן שעון שפן שקד שקית שרוך תבלין תוף תות תמר תנור תפוח תפוז תרנגול תרמיל'.split(' ')};

window.__MODS['app-lang']=1;
